In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("Raw_data.csv")
df

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,id,name,age,country,gender,income
0,0,0,0,1,John Doe,29.0,USA,Male,55000.0
1,1,1,1,2,Jane Smith,❌,Canada,Female,62000.0
2,2,2,2,3,Alex,❌,USA,Unknown,47000.0
3,3,3,3,4,Maria Garcia,34.0,Spain,Female,❌
4,4,4,4,5,Li Wei,27.0,China,Male,51000.0
5,5,5,5,6,❌,45.0,India,Female,73000.0
6,6,6,6,7,Ahmed Khan,38.0,❌,Male,68000.0
7,7,7,7,8,Rachel Lee,29.0,USA,Female,62000.0
8,8,8,8,9,Carlos Ruiz,❌,Mexico,Male,45000.0
9,9,9,9,10,Emily Davis,31.0,USA,❌,58000.0

In [4]:
# CLEANING OF DATA :: 👇
# 1.IS NULL ::
df.isnull()
df.isna()

# 2. CHAINING OF DIFFERENT FUNCTION isnull() + sum()
df.isnull().sum()

# 3. DROIPPING OF THE NULL VALUES FROM THE DATA LIKE THIS
df.dropna()  # dropping only the row
df.dropna(axis = 1)  # this will drop the column

# 4. FILLING IN PLACE OF THE MISSING VALUE WITH SOME DESIRED PARTICULAR VALUE
df.fillna("❌")

# 5. FORWARD FILLING IS DONE LIKE THIS 
df.ffill()

# 6. BACKWARD FILLING IS DONE LIKE THIS 
df.bfill()

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,id,name,age,country,gender,income
0,0,0,0,1,John Doe,29.0,USA,Male,55000.0
1,1,1,1,2,Jane Smith,❌,Canada,Female,62000.0
2,2,2,2,3,Alex,❌,USA,Unknown,47000.0
3,3,3,3,4,Maria Garcia,34.0,Spain,Female,❌
4,4,4,4,5,Li Wei,27.0,China,Male,51000.0
5,5,5,5,6,❌,45.0,India,Female,73000.0
6,6,6,6,7,Ahmed Khan,38.0,❌,Male,68000.0
7,7,7,7,8,Rachel Lee,29.0,USA,Female,62000.0
8,8,8,8,9,Carlos Ruiz,❌,Mexico,Male,45000.0
9,9,9,9,10,Emily Davis,31.0,USA,❌,58000.0

In [5]:
# DUPLICATE REMOVAL FROM THE DATA :: 👇

# 1. FIRST TO CHECK IF THERE IS ANY DUPLICATE DATA IS THERE OR NOT
df.duplicated()

# 1.a TO CHECK FOR SOME SPECIFIC VALUES , THEN DO LIKE THIS 
df["country"].duplicated()

# 1.b ON SET OF COLUMNS LIKE THIS 
df[["country" , "gender"]].duplicated()

# 2. REMOVAl OF DUPLICATES LIKE THIS ::👇
df.drop_duplicates()

# MAKING THE COPY OF THE DATA SUCH AS TO REFLECT THE CHANGES IN IT , THAT I AM DOING HERE
df2 = df.copy()
df.drop_duplicates()

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,id,name,age,country,gender,income
0,0,0,0,1,John Doe,29.0,USA,Male,55000.0
1,1,1,1,2,Jane Smith,❌,Canada,Female,62000.0
2,2,2,2,3,Alex,❌,USA,Unknown,47000.0
3,3,3,3,4,Maria Garcia,34.0,Spain,Female,❌
4,4,4,4,5,Li Wei,27.0,China,Male,51000.0
5,5,5,5,6,❌,45.0,India,Female,73000.0
6,6,6,6,7,Ahmed Khan,38.0,❌,Male,68000.0
7,7,7,7,8,Rachel Lee,29.0,USA,Female,62000.0
8,8,8,8,9,Carlos Ruiz,❌,Mexico,Male,45000.0
9,9,9,9,10,Emily Davis,31.0,USA,❌,58000.0

In [6]:
# DATA_TYPES :: 👇

# 1. TO FIND OUT THE DIFFERENT TYPES OF DATA TYPES IN THE DATA ::
df.dtypes

# 2. TO CHANGE THE DATA TYPE OF ANY OF THE FUNCTION 
# df = df.fillna(0)
df["age"].astype("int64")

ValueError: invalid literal for int() with base 10: '29.0'

In [ ]:
# FEATURE ENGINEERING :: 👇

# FIRST MAKING A COPY THE ORIGINAL DATA 
df2 = df.copy()

# 1. APPLY () :- 
# NOW MAKING OF THE FUNCTION THAT I WILL BE PASSING IN THE TAX COLUMN TO CALCULATE IT AUTOMATICALLY
# a. GENERAL WAY OF DECLARING A FUNCTION THEN PASSING IT LIKE THIS 
# def tax(income):
#     if(income > 50000):
#         return "20%"
#     else:
#         return "10%"

# b. USING OF THE LAMBDA FUNCTON LIKE THIS :-
# df2["tax"] = df2["income"].apply(lambda x: "20%" if x >= 50000 else "10%")
# df2

# 2. MAPPING OF EXSITING DATA WITH THE NEW DATA , like this 
# gender_map = {"Male" : "M" , "Female" : "F" , "Unknown" : "U"}
# df2["gender"].map(gender_map)

# TO MAKE IT GET IN THE REAL / ORIGINAL DATA , DO IT LIKE THIS 
# df2["gender"] = df2["gender"].map(gender_map)
# df2

# 3. ASSIGN , CREATION OF NEW COLUMN WITH SOME ACTUAL DATA IN IT AND ALSO MAKE IT AVAILABLE IN THE REAL DATA
# df2.assign(new_income =df2["income"] * 1.1)
# df2 = df2.assign(new_income =df2["income"] * 1.1)

# 4. REPLACE FUNTION USE ::
# df2["country"] = df2["country"].replace("USA" , "US")
# df2

# 5. RENAME :-
# df2.columns =["ID" , "NAME" , "AGE" , "COUNTRY" , "GENDER" , "INCOME"]
# print(df2)

# df2.rename(columns = {"INCOME" : "SALARY"})
# df2.rename(index = {1 : "FIRST"})

# 6. SORTING FUNCTION ::
# df2["income"].sort_values()

# OR TO PRINT FULL TABLE , DO LIKE THIS 
# df2.sort_values("income")
# df2.sort_values("age")

# NOW COMBINING BOTH THE PARAMETERS TO GET THE OUTPUT :: 
# df2.sort_values(["income","age"])

# NOW IN DESCENDING ORDER LIKE THIS
sorted_df = df2.sort_values("income" , ascending= False)
# NOW USING THE SORTING INDEX , LIKE THIS 
sorted_df.sort_index()

# RESET INDEX FUNCTION ::
sorted_df.reset_index()

# THIS IS HOW U GIVE RANKS ::
# sorted_df["RANKING"] = sorted_df["income"].rank()

# MAKING 1 AS THE HIGHEST 
sorted_df["RANKING"] = sorted_df["income"].rank(ascending= False)
sorted_df

In [ ]:
# WRITING DATA IN CSV & JSON , LIKE THIS ::
df3 = pd.read_csv("Raw_data.csv")
df4 = df3.copy()
df4 = df4.drop_duplicates()
df4 = df4.fillna("❌")

df4 = df4.reset_index(drop = True)
df4.to_csv("Raw_data.csv")

In [ ]:
# GROUPING & AGGREGATION OF DATA ::
# 1. FIRST U HAVE TO GROUP THE DATA 
# df.groupby("country")

# 2. THEN U HAVE TO USE THE AGGREGATION FUNCTION WITH THE GROUPBY AS LIKE IT IS A CONDITON 
# ON WHAT BASIS U HAVE TO GROPU THEM , LIKE THIS 
# df.groupby("country")["income"].mean()

# U CAN USE MORE AGGREGATINON FUNCTIONS LIKE THIS 
# 1. SUM 
# df.groupby("country")["income"].sum()
# 2. MAX
# df.groupby("country")["income"].max()
# 3. MIN 
df.groupby("country")["income"].min()
# 4. COUNT 
df.groupby("country")["income"].count()

# ON THE BASIS OF GENDER IF I WANT TO FIND THE MEAN THEN DO IT LIKE THIS ::
df.groupby("gender")["income"].mean()

# FINDING THE SUM OF THE EACH GENDER INCOME 
df.groupby("gender")["income"].sum()

# FINDING THE MEAN OF THE AGE OF EACH GENDER LIKE THIS 
df.groupby("gender")["age"].mean()

# FINDING THE MEAN OF THE AGE OF EACH COUNTRY LIKE THIS 
df.groupby("country")["age"].mean()

# USE OF AGG IS LIKE THIS ::
df.groupby("country")["income"].agg(mean_salary = "mean" , min_salary = "min" , max_salary = "max" , SUM = "sum" , COUNT = "count")

# PERFORMING DIFF DIFF AGGREGATION FUNCTIONS ON DIFF DIFF COLUMNS TOGETHER LIKE THIS 
df.groupby("country").agg({
    "income" : "mean",
    "age" : "max"
})

In [ ]:
df = pd.read_csv("Employee_data.csv")
df

In [ ]:
# BASIC VISULAIZATION IN PANDA ::
# 1. HISTOGRAM () ::
# going to plot the histogram on the age like this 
# df["Age"].hist()

# 2. PLOT() ::
df.plot(kind= "scatter" , x = "Age" , y = "Salary")

NameError: name 'df' is not defined